export const courseConfigs = {
  'vibecoding': {
    courseId: 'vibecoding',
    courseTitle: 'Vibe Coding',
    basePath: '/vibecoding',
    modules: [
      { slug: 'module-1-philosophy', title: '1. The Philosophy' },
      { slug: 'module-2-toolkit', title: '2. The Modern Toolkit' },
      { slug: 'module-3-prompts', title: '3. The Art of the Prompt' },
      { slug: 'module-4-lab', title: '4. Lab: Name Generator' },
      { slug: 'module-5-product', title: '5. To Professional Product' },
      { slug: 'module-6-debugging', title: '6. Debugging & Iteration' },
      { slug: 'module-7-deployment', title: '7. Deployment & Databases' },
    ],
  },
  'prompt': {
    courseId: 'prompt',
    courseTitle: 'Prompt Engineering',
    basePath: '/prompt',
    modules: [
      { slug: 'module-1-core-idea', title: '1. The Core Idea' },
      { slug: 'module-2-core-techniques', title: '2. Core Techniques' },
      { slug: 'module-3-advanced-reasoning', title: '3. Advanced Reasoning' },
      { slug: 'module-4-code-prompting', title: '4. Code Prompting' },
      { slug: 'module-5-best-practices', title: '5. Best Practices' },
      { slug: 'module-6-rag-functions', title: '6. RAG & Functions' },
      { slug: 'module-7-chaining-agents', title: '7. Chaining & Agents' },
    ],
  },
  'automation': {
    courseId: 'automation',
    courseTitle: 'AI Automation',
    basePath: '/automation',
    modules: [
      { slug: 'module-1-mindset', title: '1. The Automation Mindset' },
      { slug: 'module-2-apis', title: '2. API Fundamentals' },
      { slug: 'module-3-nocode', title: '3. No-Code Automation' },
      { slug: 'module-4-agents', title: '4. AI Agents' },
      { slug: 'module-5-mcp-automation', title: '5. MCP Automation' },
      { slug: 'module-6-pipelines', title: '6. Custom Pipelines' },
      { slug: 'module-7-production', title: '7. Production' },
    ],
  },
  'mcp': {
    courseId: 'mcp',
    courseTitle: 'MCP Development',
    basePath: '/mcp',
    modules: [
      { slug: 'module-1-what-is-mcp', title: '1. What is MCP' },
      { slug: 'module-2-transports', title: '2. Transports' },
      { slug: 'module-3-first-server', title: '3. First Server' },
      { slug: 'module-4-primitives', title: '4. Primitives' },
      { slug: 'module-5-clients', title: '5. Clients' },
      { slug: 'module-6-real-world', title: '6. Real World' },
      { slug: 'module-7-production', title: '7. Production' },
    ],
  },
  'agentic': {
    courseId: 'agentic',
    courseTitle: 'The Agentic Web',
    basePath: '/agentic',
    modules: [
      { slug: 'module-1-core-idea', title: '1. The Core Idea' },
      { slug: 'module-2-components', title: '2. Components' },
      { slug: 'module-3-dimensions', title: '3. Dimensions' },
      { slug: 'module-4-applications', title: '4. Applications' },
      { slug: 'module-5-future', title: '5. The Future' },
      { slug: 'module-6-protocols', title: '6. Protocols' },
      { slug: 'module-7-build-agent', title: '7. Build an Agent' },
    ],
  },
  'web3': {
    courseId: 'web3',
    courseTitle: 'Web3 Fundamentals',
    basePath: '/web3',
    modules: [
      { slug: 'module-1-vision', title: '1. The Vision' },
      { slug: 'module-2-bedrock', title: '2. The Bedrock' },
      { slug: 'module-3-smart-contracts', title: '3. Smart Contracts' },
      { slug: 'module-4-ecosystem', title: '4. The Ecosystem' },
      { slug: 'module-5-getting-started', title: '5. Getting Started' },
      { slug: 'module-6-future', title: '6. The Future' },
      { slug: 'module-7-layer2s', title: '7. Layer 2s' },
      { slug: 'module-8-tokenomics', title: '8. Tokenomics' },
    ],
  },
  'vibecoding-bootcamp': {
    courseId: 'vibecoding-bootcamp',
    courseTitle: 'Vibe Coding Bootcamp',
    basePath: '/vibecoding/bootcamp',
    modules: [
      { slug: 'day-1-ai-foundations', title: 'Day 1 - AI Foundations' },
      { slug: 'day-2-second-brain', title: 'Day 2 - Second Brain + AI' },
      { slug: 'day-3-ai-for-organizations', title: 'Day 3 - AI for Organizations' },
      { slug: 'day-4-vibe-coding', title: 'Day 4 - Build Your First App' },
      { slug: 'day-5-polish-and-power', title: 'Day 5 - Polish and Power' },
      { slug: 'day-6-ship-and-grow', title: 'Day 6 - Ship and Grow' },
      { slug: 'day-7-sell-and-beyond', title: 'Day 7 - Sell and Beyond' },
    ],
  },
} as const;

export type CourseId = keyof typeof courseConfigs;
