export const courseConfigs = {
  'vibe-coding': {
    courseId: 'vibe-coding',
    courseTitle: 'Vibe Coding 101',
    basePath: '/vibe-coding',
    modules: [
      { slug: 'module-1-philosophy', title: '1. The Philosophy' },
      { slug: 'module-2-toolkit', title: '2. The Modern Toolkit' },
      { slug: 'module-3-prompts', title: '3. The Art of the Prompt' },
      { slug: 'module-4-lab', title: '4. Lab: Name Generator' },
      { slug: 'module-5-product', title: '5. To Professional Product' },
      { slug: 'module-6-debugging', title: '6. Debugging & Iteration' },
      { slug: 'module-7-deployment', title: '7. Deployment & Databases' },
    ],
  },
  'prompt-engineering-101': {
    courseId: 'prompt-engineering-101',
    courseTitle: 'Prompt Engineering 101',
    basePath: '/prompt-engineering-101',
    modules: [
      { slug: 'module-1-core-idea', title: '1. The Core Idea' },
      { slug: 'module-2-core-techniques', title: '2. Core Techniques' },
      { slug: 'module-3-advanced-reasoning', title: '3. Advanced Reasoning' },
      { slug: 'module-4-code-prompting', title: '4. Code Prompting' },
      { slug: 'module-5-best-practices', title: '5. Best Practices' },
      { slug: 'module-6-rag-functions', title: '6. RAG & Functions' },
      { slug: 'module-7-chaining-agents', title: '7. Chaining & Agents' },
    ],
  },
  'ai-automation': {
    courseId: 'ai-automation',
    courseTitle: 'AI Automation 101',
    basePath: '/ai-automation',
    modules: [
      { slug: 'module-1-mindset', title: '1. The Automation Mindset' },
      { slug: 'module-2-apis', title: '2. API Fundamentals' },
      { slug: 'module-3-nocode', title: '3. No-Code Automation' },
      { slug: 'module-4-agents', title: '4. AI Agents' },
      { slug: 'module-5-mcp-automation', title: '5. MCP Automation' },
      { slug: 'module-6-pipelines', title: '6. Custom Pipelines' },
      { slug: 'module-7-production', title: '7. Production' },
    ],
  },
  'mcp-development': {
    courseId: 'mcp-development',
    courseTitle: 'MCP Development 101',
    basePath: '/mcp-development',
    modules: [
      { slug: 'module-1-what-is-mcp', title: '1. What is MCP' },
      { slug: 'module-2-transports', title: '2. Transports' },
      { slug: 'module-3-first-server', title: '3. First Server' },
      { slug: 'module-4-primitives', title: '4. Primitives' },
      { slug: 'module-5-clients', title: '5. Clients' },
      { slug: 'module-6-real-world', title: '6. Real World' },
      { slug: 'module-7-production', title: '7. Production' },
    ],
  },
  'agentic-web': {
    courseId: 'agentic-web',
    courseTitle: 'The Agentic Web',
    basePath: '/agentic-web',
    modules: [
      { slug: 'module-1-core-idea', title: '1. The Core Idea' },
      { slug: 'module-2-components', title: '2. Components' },
      { slug: 'module-3-dimensions', title: '3. Dimensions' },
      { slug: 'module-4-applications', title: '4. Applications' },
      { slug: 'module-5-future', title: '5. The Future' },
      { slug: 'module-6-protocols', title: '6. Protocols' },
      { slug: 'module-7-build-agent', title: '7. Build an Agent' },
    ],
  },
  'web3-101': {
    courseId: 'web3-101',
    courseTitle: 'Web3 101',
    basePath: '/web3-101',
    modules: [
      { slug: 'module-1-vision', title: '1. The Vision' },
      { slug: 'module-2-bedrock', title: '2. The Bedrock' },
      { slug: 'module-3-smart-contracts', title: '3. Smart Contracts' },
      { slug: 'module-4-ecosystem', title: '4. The Ecosystem' },
      { slug: 'module-5-getting-started', title: '5. Getting Started' },
      { slug: 'module-6-future', title: '6. The Future' },
      { slug: 'module-7-layer2s', title: '7. Layer 2s' },
      { slug: 'module-8-tokenomics', title: '8. Tokenomics' },
    ],
  },
} as const;

export type CourseId = keyof typeof courseConfigs;
