/**
 * Single source of truth for URL redirects and known route groups.
 * Imported by next.config.mjs (redirects) and scripts/generate-agent-manifest.ts
 * (agent validity + markdown manifests), so both always agree.
 */

/** Old long essay slugs -> current root slugs. */
export const ESSAY_SLUG_MIGRATIONS = [
  ['agent-infrastructure-stack', 'agentstack'],
  ['agentic-commerce', 'agentcommerce'],
  ['agentic-state', 'stateagents'],
  ['agents-eating-saas', 'agentsaas'],
  ['agi-governance', 'governance'],
  ['ai-agent-economy', 'agenteconomy'],
  ['ai-economy', 'aieconomy'],
  ['ai-implementation-playbook', 'playbook'],
  ['ambient-intelligence', 'ambient'],
  ['api-states', 'apis'],
  ['artificial-intuition', 'intuition'],
  ['asi-timeline', 'asi'],
  ['attention-refinery', 'attention'],
  ['blockchain-journey', 'blockchain'],
  ['bureaucracy-tax', 'bureaucracy'],
  ['cheap-to-competitive', 'competitive'],
  ['cognitive-load', 'cognition'],
  ['computational-constitutions', 'constitutions'],
  ['computational-social-science', 'socialscience'],
  ['dark-forest-internet', 'darkforest'],
  ['digital-monasticism', 'monasticism'],
  ['god-protocol', 'godprotocol'],
  ['great-funding-realignment', 'funding'],
  ['hustle-culture', 'hustle'],
  ['in-between-state', 'liminal'],
  ['infinity-economy', 'infinity'],
  ['internet-of-lies', 'lies'],
  ['intuitive-singularity', 'instinct'],
  ['mesh-economy', 'mesh'],
  ['plurality-trap', 'plurality'],
  ['post-interface-internet', 'postinterface'],
  ['post-scarcity-technology', 'postscarcity'],
  ['programmable-trust', 'trust'],
  ['pseudonymous-agency', 'pseudonymity'],
  ['rationality-in-ai', 'rationality'],
  ['revision-gap', 'revision'],
  ['sacred-algorithms', 'algorithms'],
  ['sensory-internet', 'sensory'],
  ['simulation-hypothesis', 'simulation'],
  ['simulation-layer', 'simulayer'],
  ['singapores-arc', 'singapore'],
  ['singularity-paradox', 'paradox'],
  ['state-of-ai', 'stateofai'],
  ['state-of-web3', 'stateofweb3'],
  ['stepwise-ai', 'stepwise'],
  ['substrate-shift', 'substrate'],
  ['synthetic-empathy', 'empathy'],
  ['towards-the-agentic-web', 'agenticweb'],
  ['twilight-economy', 'twilight'],
  ['universal-text-ui', 'textui'],
  ['yc-landscape', 'yc'],
];

/** Non-essay redirects: [source path prefix, destination]. ':path*' suffixes preserved. */
export const EXTRA_REDIRECTS = [
  ['/who-buys', '/receipts'],
  ['/writings', '/essays'],
  ['/194', '/agenticweb'],
  ['/158', '/blockchain'],
  ['/profile', '/about'],
  ['/about-us', '/about'],
  ['/about-us/:path*', '/about'],
  ['/about-me', '/about'],
  ['/who', '/about'],
  ['/author', '/about'],
  ['/bio', '/about'],
  ['/team', '/about'],
  ['/press', '/media'],
  ['/news', '/media'],
  ['/speaking', '/media'],
  ['/meeting', '/contact'],
  ['/web3-101', '/web3'],
  ['/web3-101/:path*', '/web3/:path*'],
  ['/mcp-development', '/mcp'],
  ['/mcp-development/:path*', '/mcp/:path*'],
  ['/ai-automation', '/automation'],
  ['/ai-automation/:path*', '/automation/:path*'],
  ['/agentic-web', '/agentic'],
  ['/agentic-web/:path*', '/agentic/:path*'],
  ['/prompt-engineering-101', '/prompt'],
  ['/prompt-engineering-101/:path*', '/prompt/:path*'],
  ['/vibe-coding', '/vibecoding'],
  ['/vibe-coding/:path*', '/vibecoding/:path*'],
  ['/ai-reports', '/ailib'],
  ['/ai-reports/:path*', '/ailib/:path*'],
  ['/aireports', '/ailib'],
  ['/aireports/:path*', '/ailib/:path*'],
  ['/web3-reports', '/web3lib'],
  ['/web3-reports/:path*', '/web3lib/:path*'],
  ['/ai-discovery-standards', '/aistandards'],
  ['/ai-discovery-standards/:path*', '/aistandards/:path*'],
  ['/site-checklist', '/sitecheck'],
  ['/site-checklist/:path*', '/sitecheck/:path*'],
  ['/docs', '/developers'],
  ['/docs/:path*', '/developers'],
  ['/developer', '/developers'],
  ['/developer/:path*', '/developers'],
  ['/api-docs', '/developers'],
  ['/apidocs', '/developers'],
  ['/api/docs', '/developers'],
  ['/swagger.json', '/openapi.json'],
  ['/docs.json', '/openapi.json'],
  ['/openapi', '/openapi.json'],
  ['/openapi.yaml', '/openapi.json'],
  ['/openapi.yml', '/openapi.json'],
  ['/api/spec', '/openapi.json'],
  ['/auth', '/auth.md'],
  ['/auth-docs', '/auth.md'],
  ['/docs/auth', '/auth.md'],
  ['/webhooks', '/developers'],
  ['/webhooks.json', '/developers'],
  ['/docs/webhooks', '/developers'],
  ['/mcp-docs', '/developers'],
  ['/mcp-server', '/.well-known/mcp'],
  ['/mcp/docs', '/.well-known/mcp/docs'],
];

/** Pages that exist but are intentionally excluded from agent manifests and sitemaps. */
export const UNLISTED_PATHS = ['/admin', '/invoice'];
